# Project: libstpool
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = .obj/CMAllocator.o .obj/CMPool.o .obj/CTaskPool.o .obj/stpool.o .obj/tpool.o .obj/mpool.o .obj/ospx.o .obj/ospx_error.o $(RES)
LINKOBJ  = .obj/CMAllocator.o .obj/CMPool.o .obj/CTaskPool.o .obj/stpool.o .obj/tpool.o .obj/mpool.o .obj/ospx.o .obj/ospx_error.o $(RES)
LIBS =  -L"C:/Program Files/DEV-CPP/Lib"  
INCS =  -I"C:/Program Files/DEV-CPP/include"  -I"../src"  -I"../c++"  -I".." 
CXXINCS =  -I"C:/Program Files/DEV-CPP/lib/gcc/mingw32/3.4.2/include"  -I"C:/Program Files/DEV-CPP/include/c++/3.4.2/backward"  -I"C:/Program Files/DEV-CPP/include/c++/3.4.2/mingw32"  -I"C:/Program Files/DEV-CPP/include/c++/3.4.2"  -I"C:/Program Files/DEV-CPP/include"  -I"../src"  -I"../c++"  -I".." 
BIN  = libstpoolc++.a
CXXFLAGS = $(CXXINCS) -DNDEBUG -D_DISABLE_MPOOL -D_HAS_STDINT_H -D_WIN32 -D_USRDLL   -ansi -fexceptions
CFLAGS = $(INCS)   -ansi -fexceptions
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before libstpoolc++.a all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	ar r $(BIN) $(LINKOBJ)
	ranlib $(BIN)

.obj/CMAllocator.o: ../c++/CMAllocator.cpp
	$(CPP) -c ../c++/CMAllocator.cpp -o .obj/CMAllocator.o $(CXXFLAGS)

.obj/CMPool.o: ../c++/CMPool.cpp
	$(CPP) -c ../c++/CMPool.cpp -o .obj/CMPool.o $(CXXFLAGS)

.obj/CTaskPool.o: ../c++/CTaskPool.cpp
	$(CPP) -c ../c++/CTaskPool.cpp -o .obj/CTaskPool.o $(CXXFLAGS)

.obj/stpool.o: ../stpool.c
	$(CPP) -c ../stpool.c -o .obj/stpool.o $(CXXFLAGS)

.obj/tpool.o: ../src/tpool.c
	$(CPP) -c ../src/tpool.c -o .obj/tpool.o $(CXXFLAGS)

.obj/mpool.o: ../src/mpool.c
	$(CPP) -c ../src/mpool.c -o .obj/mpool.o $(CXXFLAGS)

.obj/ospx.o: ../src/ospx.c
	$(CPP) -c ../src/ospx.c -o .obj/ospx.o $(CXXFLAGS)

.obj/ospx_error.o: ../src/ospx_error.c
	$(CPP) -c ../src/ospx_error.c -o .obj/ospx_error.o $(CXXFLAGS)
